# Setup
title:               Caroline Zeng
tagline:             'software engineer'
description:         ''
url:                 https://czeng18.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Caroline Zeng
  url:               https://twitter.com/mdo
  email:             chzeng18@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: UA-146052-15
